services:
  server:
    image: nginx:1.30.4-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./ssl:/etc/nginx/ssl
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
      - ./apps/main:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
